### ISSUE TITLE
[QUESTION]  Connection issue using aiokafka with Docker Compose

### ISSUE THREAD

**Issue by 7l-hyuk** [aio-libs/aiokafka#1114]
I'm experiencing a problem when using aiokafka with Docker Compose.

At first, I only ran Zookeeper and Kafka in Docker containers, while running the producer and consumer locally on my machine. The following is the docker-compose.yml I used for that setup:

```yml
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
```

I ran the containers with:

```bash
docker compose up --build
```

The producer and consumer were written as follows:

* Producer (FastAPI):

```python
from fastapi import FastAPI
from aiokafka import AIOKafkaProducer

app = FastAPI()

KAFKA_BROKER = "localhost:29092"

async def get_producer():
    producer = AIOKafkaProducer(bootstrap_servers=KAFKA_BROKER)
    await producer.start()
    return producer


@app.post("/create-order/")
async def create_order(iter: int):
    producer = await get_producer()

    try:
        for i in range(iter):
            message = f"message{i}".encode("utf-8")
            await producer.send_and_wait("test-topic", message)
            print(f"Sent: {message}")
        return {"status": "Order request sent to Kafka"}
    finally:
        await producer.stop()
```

* Consumer (FastAPI):

```python
from contextlib import asynccontextmanager

from fastapi import FastAPI
from aiokafka import AIOKafkaConsumer, AIOKafkaProducer
import asyncio

KAFKA_BROKER = "localhost:29092"

async def get_consumer():
    consumer = AIOKafkaConsumer(
        "test-topic",
        bootstrap_servers=KAFKA_BROKER,
        group_id="order-service-group"
    )
    await consumer.start()
    return consumer


async def consume_orders():
    consumer = await get_consumer()
    try:
        async for msg in consumer:
            print(f"Comsumer Receive: {msg}")
    finally:
        await consumer.stop()


@asynccontextmanager
async def lifespan(app: FastAPI):
    asyncio.create_task(consume_orders())
    yield
    
app = FastAPI(lifespan=lifespan)
```

I ran these like this:

```bash
# Producer
uvicorn src.main:app --port 8000

# Consumer
uvicorn src.main:app --port 8001
```

This setup worked just as expected.

However, when I tried to move the producer and consumer into containers using Docker Compose, the connection to Kafka failed.

Here’s the new docker-compose.yml file I used:

```yml
services:
  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  
  service:
    build: 
      context: service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
```

Error:

```bash
zookeeper-1    | ===> User
zookeeper-1    | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
zookeeper-1    | ===> Configuring ...                                                                                                                      
kafka-1        | ===> User                                                                                                                                 
kafka-1        | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
kafka-1        | ===> Configuring ...                                                                                                                      
kafka-1        | Running in Zookeeper mode...                                                                                                              
api-gateway-1  | INFO:     Started server process [10]                                                                                                     
api-gateway-1  | INFO:     Waiting for application startup.
api-gateway-1  | INFO:     Application startup complete.                                                                                                   
api-gateway-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)                                                                   
service-1      | INFO:     Started server process [10]                                                                                                     
service-1      | INFO:     Waiting for application startup.
service-1      | INFO:     Application startup complete.                                                                                                   
service-1      | INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)                                                                   
service-1      | Unable connect to "localhost:29092": Multiple exceptions: [Errno 111] Connect call failed ('::1', 29092, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 29092)                                                                                                                                 
service-1      | Task exception was never retrieved
service-1      | future: <Task finished name='Task-3' coro=<consume_orders() done, defined at /app/src/main.py:25> exception=KafkaConnectionError("Unable to bootstrap from [('localhost', 29092, <AddressFamily.AF_UNSPEC: 0>)]")>                                                                                   
service-1      | Traceback (most recent call last):
service-1      |   File "/app/src/main.py", line 26, in consume_orders                                                                                     
service-1      |     consumer = await get_consumer()                                                                                                       
service-1      |                ^^^^^^^^^^^^^^^^^^^^                                                                                                       
service-1      |   File "/app/src/main.py", line 15, in get_consumer                                                                                       
service-1      |     await consumer.start()                                                                                                                
service-1      |   File "/app/.venv/lib/python3.12/site-packages/aiokafka/consumer/consumer.py", line 371, in start                                        
service-1      |     await self._client.bootstrap()                                                                                                        
service-1      |   File "/app/.venv/lib/python3.12/site-packages/aiokafka/client.py", line 266, in bootstrap                                               
service-1      |     raise KafkaConnectionError(f"Unable to bootstrap from {self.hosts}")                                                                  
service-1      | aiokafka.errors.KafkaConnectionError: KafkaConnectionError: Unable to bootstrap from [('localhost', 29092, <AddressFamily.AF_UNSPEC: 0>)] 
service-1      | Unclosed AIOKafkaConsumer                                                                                                                 
service-1      | consumer: <aiokafka.consumer.consumer.AIOKafkaConsumer object at 0x7998971763c0>  
```

docker ps confirms that all containers are up and Kafka is exposed on port 29092.

```bash
ce86a0690571   confluentinc/cp-kafka:7.4.3       "/etc/confluent/dock…"   About a minute ago   Up About a minute   9092/tcp, 0.0.0.0:29092->29092/tcp, [::]:29092->29092/tcp         backend-kafka-1
0bb9b4b2435e   confluentinc/cp-zookeeper:7.4.3   "/etc/confluent/dock…"   About a minute ago   Up About a minute   2888/tcp, 0.0.0.0:2181->2181/tcp, [::]:2181->2181/tcp, 3888/tcp   backend-zookeeper-1
e530a2fdb9bb   backend-api-gateway               "uv run uvicorn src.…"   About a minute ago   Up About a minute   0.0.0.0:8000->8000/tcp, [::]:8000->8000/tcp                       backend-api-gateway-1
97a22e272713   backend-service                   "uv run uvicorn src.…"   About a minute ago   Up About a minute   0.0.0.0:8001->8001/tcp, [::]:8001->8001/tcp                       backend-service-1
```

How can I fix this connection issue when using aiokafka in a containerized FastAPI app?
Is this because localhost in the container refers to itself rather than the Kafka container?

Thanks in advance for your help!
