### ISSUE TITLE
producer.stop() freezes after received ConnectionError

### ISSUE THREAD

**Issue by FedirAlifirenko** [aio-libs/aiokafka#512]
Dear all. Hello.
I am trying to create some minimal example of `producer` that will alive after Kafka becomes unavailable. It seems I found some unexpected behavior on `await producer.stop()`.
To start Kafka I am using `docker-compose up -d kafka` (the content of `docker-compose.yml` is below)
```
version: '3.2'

services:
  kafka:
    image: wurstmeister/kafka
    container_name: testkafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: testzookeeper
    ports:
      - 2181:2181
```
**Kafka version:**
`[2019-05-27 11:25:14,661] INFO Kafka version : 2.1.0 (org.apache.kafka.common.utils.AppInfoParser)`

**VENV info:**
```
(3_7_2) MacBook-Pro-2:test_produce fedir$ python -V
Python 3.7.2
(3_7_2) MacBook-Pro-2:test_produce fedir$ pip list | grep kafka
aiokafka     0.5.1  
kafka-python 1.4.3  
```

Then I run this script:
```python
import asyncio
import logging
import signal

import kafka.errors
from aiokafka.producer.producer import AIOKafkaProducer


async def produce():
    producer = AIOKafkaProducer(
        loop=asyncio.get_event_loop(),
        bootstrap_servers="localhost:9092"
    )
    while True:
        try:
            print("[producer] starting...")
            await producer.start()

            while True:
                print("[producer] sending msg...")
                await producer.send("test", value=b"1" * 100)
                await asyncio.sleep(1)

        except kafka.errors.KafkaError as err:
            if not err.retriable:
                print("[producer] Kafka non-retriable error:", err)
                break

            print("[producer] Kafka retriable error:", err)
            await asyncio.sleep(1)

        except asyncio.CancelledError:
            print("[producer] cancelled...")

        finally:
            print("[producer] stopping...")
            await producer.stop()
            print("[producer] stopped")


async def main():
    task = asyncio.create_task(produce())

    loop = asyncio.get_event_loop()
    loop.add_signal_handler(signal.SIGINT, task.cancel)

    await task
    print("task done")



if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - [%(levelname)s] - [%(name)s] - %(filename)s:%(lineno)d - %(message)s",
    )
    asyncio.run(main())

```
I am starting the script and after some seconds I stop kafka docker container by `docker stop {container_id}`. The next output is received:
```
[producer] starting...
[producer] sending msg...
...
[producer] sending msg...
2019-05-27 14:45:14,259 - [WARNING] - [aiokafka.producer.sender] - sender.py:727 - Got error produce response: ConnectionError: Connection at kafka:9092 closed
[producer] sending msg...
[producer] Kafka non-retriable error: KafkaTimeoutError
[producer] stopping...
```

- Actual result - `producer.stop()` call is awaited forever ("task done" message is never printed to console).
- Expected result - it seems `producer.stop()` call shouldn't be affected by `ConnectionError` exception. 

After some debugging I found why `producer.stop()` isn't finish.
When I set breakpoint here https://github.com/aio-libs/aiokafka/blob/master/aiokafka/producer/producer.py#L316
I see that `self._sender.sender_task` is in `PENDING` state on this step https://github.com/aio-libs/aiokafka/blob/master/aiokafka/producer/sender.py#L151
Then, following this chain 
waiters --> task --> self._send_produce_req --> handler.do --> self._client._maybe_wait_metadata
I see that we awaiting client's `_md_update_fut` Future object https://github.com/aio-libs/aiokafka/blob/master/aiokafka/client.py#L630
If I understand correctly, this future is updated in with result in `self._sync_task` https://github.com/aio-libs/aiokafka/blob/master/aiokafka/client.py#L262
Then I back to the breakpoint and see that `self._sync_task` has `FINISHED` state and `ConnectionError` exception.
As result, client's `_md_update_fut` will not be set and we will await `producer.stop()` forever.

Maybe it's needed to add some callback to client's `self._sync_task` to handle such exceptions explicitly or in some another way https://github.com/aio-libs/aiokafka/blob/master/aiokafka/client.py#L236

@tvoinarovskyi please give feedback if you'll have time
